Drop Node.js 14 support
ember-cli/ember-try pull request #920
Opened 2023-03-02 18:33 UTC by SergeAstapov

Follow up to #913

2023-03-02 21:21 UTC, hjdivad reviewed
Can you look into [the failing tests](https://github.com/ember-cli/ember-try/pull/920/checks#step:5:121)

As in #913 the floating deps test is expected to fail, but the rest should be green.

2023-03-02 21:21 UTC, hjdivad commented
@SergeAstapov

2023-03-02 21:57 UTC, SergeAstapov commented
@hjdivad it seems never version of npm bundled with Node.js 16 cause a hard error because `ember-try-test-suite-helper@0.0.1` [specific here](https://github.com/ember-cli/ember-try/blob/master/test/fixtures/package.json) actually does not exist on npm (only 1.0.0 and 1.0.1 have been published)

it seems more correctly to actually publish that version to npm, wonder if @kategengler can do so.

meanwhile I'll try to look if there is something else missing or I can came up with a workaround

2023-03-03 10:30 UTC, mansona commented
Hey folks 👋  https://github.com/ember-cli/ember-try/pull/893 has CI passing and works around that problem you also identified @SergeAstapov

2023-08-15 18:45 UTC, kategengler requested changes
Changes requested from @mansona

2023-08-15 18:45 UTC, kategengler commented on lib/dependency-manager-adapters/npm.js
> +        // in npm we need to always add an override if the version is a pre-release
There isn't a separate adapter for yarn, so this will add it for that as well

2023-08-15 18:45 UTC, kategengler commented on lib/dependency-manager-adapters/npm.js
> +          packageJSON.overrides[packageName] = `$${packageName}`;
We should add tests for this behavior

2023-08-15 20:45 UTC, mansona commented on lib/dependency-manager-adapters/npm.js
> +          packageJSON.overrides[packageName] = `$${packageName}`;
done!

2023-08-15 21:29 UTC, mansona commented on smoke-test-app/tests/dummy/config/ember-try.js
> +          overrides: {
yes good catch! I had forgotten they were there 🙈

2023-08-15 21:58 UTC, kategengler approved these changes

2023-08-15 21:58 UTC, kategengler commented
Thank you!!

2023-08-15 21:58 UTC, merged